#version: "3.8"
# Stack de servi√ßos mysql + interface web
services:
  mysql:
    image: mysql:latest
    container_name: mysql_server_tads
    environment:
      MYSQL_ROOT_PASSWORD: <senha>
      MYSQL_USER: <usuario>
      MYSQL_PASSWORD: <senha_usuario>
      MYSQL_DATABASE: open_weather_map
    ports:
      - 3310:3306
  
  phpmyadmin:
    image: phpmyadmin
    container_name: pma_interface_tads
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  coleta_dados_armazena:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./coleta_armazenamento_ddd/coleta_armazena.py:/app/coleta_armazena.py
      - ./coleta_armazenamento_ddd/requirements.txt:/app/requirements.txt
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: siriusb
      MYSQL_PASSWORD: sirius
      MYSQL_DATABASE: open_weather_map
    